/**
 * @file Automatically generated by barrelsby.
 */

import * as alphabetats from "test/alpha/beta";
import * as etats from "test/eta";
import * as gammadeltaepsilonts from "test/gamma/delta/epsilon";
export const alpha = {
  beta: alphabetats,
};
export {etats as eta};
export const gamma = {
  delta: {
    epsilon: gammadeltaepsilonts,
  },
};
