/**
 * @file Automatically generated by barrelsby.
 */

import * as alphabetats from "./alpha/beta";
import * as etats from "./eta";
import * as gammadeltaepsilonts from "./gamma/delta/epsilon";
import * as gammazetats from "./gamma/zeta";
export const alpha = {
  beta: alphabetats,
};
export {etats as eta};
export const gamma = {
  delta: {
    epsilon: gammadeltaepsilonts,
  },
  zeta: gammazetats,
};
