import * as TestUtilities from '../testUtilities';
import { addHeaderPrefix } from './header';

describe('builder/header module has a', () => {
  describe('addHeaderPrefix function that', () => {
    it('should add a header prefix to the specified string', () => {
      TestUtilities.assertMultiLine(
        addHeaderPrefix('Test Content'),
        `/**
 * @file Automatically generated by barrelsby.
 */

Test Content`
      );
    });
  });
});
